// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBceJeIKHz7e-STZaYD09aj2yVBVhUgVDY',
    appId: '1:719431328756:web:4a881ae4878691f8258fa1',
    messagingSenderId: '719431328756',
    projectId: 'chat-f7349',
    authDomain: 'chat-f7349.firebaseapp.com',
    storageBucket: 'chat-f7349.firebasestorage.app',
    measurementId: 'G-NCDRCLT4HD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFIiPiXJmHk_eJkeaySxwp-HYXS1w518s',
    appId: '1:719431328756:android:35035226d91b04bb258fa1',
    messagingSenderId: '719431328756',
    projectId: 'chat-f7349',
    storageBucket: 'chat-f7349.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAey3s83RYsvK7gsvrI-FE1HhUlrau_MaI',
    appId: '1:719431328756:ios:f24b971fb7bfcd77258fa1',
    messagingSenderId: '719431328756',
    projectId: 'chat-f7349',
    storageBucket: 'chat-f7349.firebasestorage.app',
    iosBundleId: 'com.example.whats',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAey3s83RYsvK7gsvrI-FE1HhUlrau_MaI',
    appId: '1:719431328756:ios:f24b971fb7bfcd77258fa1',
    messagingSenderId: '719431328756',
    projectId: 'chat-f7349',
    storageBucket: 'chat-f7349.firebasestorage.app',
    iosBundleId: 'com.example.whats',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBceJeIKHz7e-STZaYD09aj2yVBVhUgVDY',
    appId: '1:719431328756:web:e249fc2e93a21cb3258fa1',
    messagingSenderId: '719431328756',
    projectId: 'chat-f7349',
    authDomain: 'chat-f7349.firebaseapp.com',
    storageBucket: 'chat-f7349.firebasestorage.app',
    measurementId: 'G-18E1DX1EGJ',
  );
}
